### ISSUE TITLE
Configure Asciidoc Maven plugin to preserve directories

### ISSUE THREAD

**Issue by der-imp** [st-tu-dresden/st-lab#21]
Please add 
`<preserveDirectories>true</preserveDirectories>`
in Asciidoc -> executions -> execution -> configuration
to st-lab/parent/pom.xml to support subdirectories in asciidoc folder.
Thank you.

**Comment by olivergierke** [comment]
Care to prepare a pull request?

**Comment by der-imp** [comment]
We want to use a new asciidoc folder structure with subfolders this semester. So yes its important to deploy this change.

**Comment by olivergierke** [comment]
I get that. That’s why i wonder if you could just prepare everything you need in a PR.

**Comment by olivergierke** [comment]
That's merged.
