### ISSUE TITLE
overwrites files with same name but different locations

### ISSUE THREAD

**Issue by SvenSeemann** [st-tu-dresden/st-lab#8]
e.g. this structure would overwrite one version of the file on "mvn package -P ci".
asciidoc/templates/pflichtenheft.adoc (the provided template)
asciidoc/pflichtenheft.adoc (the groups artifact)

**Comment by olivergierke** [comment]
Did you check whether it's the Asciidoctor rendering that produces the overwrite or do the files end up overwritten in the assembled ZIP?

**Comment by martinmo** [comment]
This was fixed via #21 in a34420c792f45eb99ae60bc7f50ba2f64e56ace3.
